### ISSUE TITLE
NPE when plugin is disabled because Geyser or Floodgate are not present

### ISSUE THREAD

**Issue by Hosairis** [DoctorMacc/GeyserPreventServerSwitch#8]
When loading the plugin on velocity I encounter this problem

`09:25:34] [Velocity Async Event Executor - #0/ERROR] [geyserpreventserverswitch]: Floodgate or Geyser not found! Disabling...
[09:25:34] [Velocity Async Event Executor - #0/ERROR] [com.velocitypowered.proxy.event.VelocityEventManager]: Couldn't pass ProxyInitializeEvent to geyserpreventserverswitch
java.lang.NullPointerException: Cannot invoke "com.github.camotoy.geyserpreventserverswitch.common.DataHandler.disable()" because "this.dataHandler" is null
	at com.github.camotoy.geyserpreventserverswitch.velocity.VelocityPreventServerSwitch.shutdown(VelocityPreventServerSwitch.java:63) ~[?:?]
	at com.github.camotoy.geyserpreventserverswitch.velocity.VelocityPreventServerSwitch.onProxyInitialize(VelocityPreventServerSwitch.java:47) ~[?:?]
	at com.github.camotoy.geyserpreventserverswitch.velocity.Lmbda$1.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.2.0.jar:3.2.0-SNAPSHOT (git-7f776abf-b252)]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]`

I use java 17 and my velocity version is the latest also the plugin version is 1.4

**Comment by Konicai** [comment]
The error message itself could be improved, but the actual issue is

> Floodgate or Geyser not found!
